### ISSUE TITLE
[功能建议] 

### ISSUE THREAD

**Issue by neverfelly** [UESTC-Course/uestc-course#38]
**功能建议**
- 建议新建一个Organization管理此项目，课程一个repo，考研一个repo
- 建议课程目录下按照各个学院分类，公选课分类在公选下
- 建议开放实验报告（实验报告真的应该传承下去

**其他**
后续会想建立一个gitbook作为课程说明

**Comment by Xovee** [comment]
谢谢反馈。
- 关于第一点，因为现在我们手里的考研资源稀少，故考研的相关部分还未实际运行。设立组织很有趣，但也许repo亦已足够；
- 因为各种课程不单属于某个学院，例如 A 学生可以选修 B 学院的课，交叉的情况也很频繁，我认为单设一个大文件夹，以课程名的粒度足以帮助学生快速定位课程；
- 实验报告的我觉得有两个 concerns
  - 实验报告应只由本人或经本人授权才可上传
  - 抄袭问题

再次表示感谢，如果您有可以贡献的资源，还请不吝分享。：）

**Comment by Xovee** [comment]
谢谢反馈。
- 关于第一点，因为现在我们手里的考研资源稀少，故考研的相关部分还未实际运行。设立组织很有趣，但也许repo亦已足够；
- 因为各种课程不单属于某个学院，例如 A 学生可以选修 B 学院的课，交叉的情况也很频繁，我认为单设一个大文件夹，以课程名的粒度足以帮助学生快速定位课程；
- 实验报告的我觉得有两个 concerns
  - 实验报告应只由本人或经本人授权才可上传
  - 抄袭问题

再次表示感谢，如果您有可以贡献的资源，还请不吝分享。：）

**Comment by MortonWang** [comment]
- Organization 的建议不错
- 课程考研分开的话不便于管理，后续如果资料很多的话可能会考虑分开
- 学院之间会有很多重合和相似的课程，这样直接用课程来分类便于查看和筛选相似课程
- 公选课程之所以没有单独出来，一是因为公选课程的划分每年变化较大，二是对于有些公选课程，不同专业学生的培养计划也不同，导致学生对相同课程的定位不同
- gitbook 的受众会不会有点窄呀，感觉周围的学生们没什么人在用

感谢反馈，谢谢支持。

**Comment by neverfelly** [comment]
- 关于Organization,主要是为了在非代码repo中进行频繁的pull操作比较耗时，member拥有的自由度更大一点（也更便于传承
- gitbook主要是为了对课程进行说明，提醒学弟学妹们课程的一些注意事项
(最近在准备把计院本科资料全部上传，包括本人的实验报告

**Comment by Xovee** [comment]
非常感谢你能为仓库的建设出力。
- Organization 我已建立，并向你发出邀请
- 实验报告似可在课程目录中另建文件夹，取名**实验**或**实验材料**，附 README 文件加以说明；或直接并入作业模板，取名**作业及实验**

**Comment by Xovee** [comment]
关闭 Issue
